### ISSUE TITLE
Page not found on link 

### ISSUE THREAD

**Issue by DylanMeeus** [paypal/paypal.github.com#32]
Hey,

This page: https://www.paypal.com/us/webapps/mpp/logos-buttons
has a link to generate a JS PayPal button at the bottom. It says: (Create a Javascript Button)

However, this points to a page that no longer exists: http://paypal.github.io/JavaScriptButtons/

**Comment by hozefaj** [comment]
@DylanMeeus Thanks for pointing it out. We will update the link to the correct one.

**Comment by hozefaj** [comment]
@DylanMeeus The issue is now fixed. @lmarkus You can close this issue.
